### ISSUE TITLE
Agent won't start

### ISSUE THREAD

**Issue by rgupta1234** [rafaeltuelho/jboss-eap-managed-on-docker#5]
Any thoughts? 
2015-10-16 15:45:17,814 INFO  [main](org.rhq.core.pc.PluginContainer)\- Plugin container is already shut down.
2015-10-16 15:45:17,817 WARN  [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.failed-to-shutdown-component}Agent failed to shutdown component [Plugin Container]. Cause: java.lang.NullPointerException:null
2015-10-16 15:45:17,817 DEBUG [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.notifying-server-of-shutdown}Agent is notifying the server that it is shutting down.
2015-10-16 15:45:17,817 DEBUG [main](org.rhq.enterprise.agent.SecurityTokenCommandPreprocessor)\- {SecurityTokenCommandPreprocessor.no-security-token-yet}There is no security token yet - the server will not accept commands from this agent until the agent is registered.
2015-10-16 15:45:17,818 DEBUG [ClientCommandSenderTask Timer Thread #0](enterprise.communications.command.client.JBossRemotingRemoteCommunicator)\- {JBossRemotingRemoteCommunicator.init-callback-done}The initialize callback has finished. Callback to be invoked again? [true]
2015-10-16 15:45:17,837 DEBUG [main](enterprise.communications.command.client.ClientRemotePojoFactory)\- {ClientRemotePojoFactory.execution-failure}Failed to execute remote POJO method [agentIsShuttingDown]. Cause: org.rhq.enterprise.communications.command.server.AuthenticationException:Command failed to be authenticated!  This command will be ignored and not processed: Command: type=[remotepojo]; cmd-in-response=[false]; config=[{rhq.agent-name=eap-slave2, rhq.externalizable-strategy=AGENT, rhq.timeout=10000}]; params=[{targetInterfaceName=org.rhq.core.clientapi.server.core.CoreServerService, invocation=NameBasedInvocation[agentIsShuttingDown]}]
2015-10-16 15:45:17,838 WARN  [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.server-shutdown-notification-failure}Agent failed to notify the server of the pending shutdown. Cause: org.rhq.enterprise.communications.command.server.AuthenticationException:Command failed to be authenticated!  This command will be ignored and not processed: Command: type=[remotepojo]; cmd-in-response=[false]; config=[{rhq.agent-name=eap-slave2, rhq.externalizable-strategy=AGENT, rhq.timeout=10000}]; params=[{targetInterfaceName=org.rhq.core.clientapi.server.core.CoreServerService, invocation=NameBasedInvocation[agentIsShuttingDown]}]
2015-10-16 15:45:17,838 DEBUG [RHQ Server Polling Thread](enterprise.communications.command.client.ServerPollingThread)\- {ServerPollingThread.stopped}Server polling thread has been stopped
2015-10-16 15:45:17,840 DEBUG [main](org.jboss.remoting.InvokerRegistry)\- removed org.jboss.remoting.transport.http.HTTPClientInvoker@68cdb8b5 from registry
2015-10-16 15:45:17,840 DEBUG [main](org.jboss.remoting.Client)\- Client[1420615797:4sh0q-82uaqb-ifttl04b-1-ifttl0fu-3] is disconnected
2015-10-16 15:45:17,840 DEBUG [main](enterprise.communications.command.client.ClientCommandSender)\- {ClientCommandSender.spooling}Persisting commands with guaranteed delivery to the spool file
2015-10-16 15:45:17,841 DEBUG [main](enterprise.communications.command.client.ClientCommandSender)\- {ClientCommandSender.spool-done}Persisted [0] commands to the spool file for later delivery to [remoting endpoint [servlet://jon-server:7080/jboss-remoting-servlet-invoker/ServerInvokerServlet/?generalizeSocketException=true]]; [0] volatile commands remain in the queue and will be lost if the sender does not start again
2015-10-16 15:45:17,841 DEBUG [main](enterprise.communications.command.client.ClientCommandSender)\- {ClientCommandSender.no-longer-sending}Client is no longer actively sending commands to [remoting endpoint [servlet://jon-server:7080/jboss-remoting-servlet-invoker/ServerInvokerServlet/?generalizeSocketException=true]]
2015-10-16 15:45:17,841 DEBUG [main](enterprise.communications.command.client.ClientCommandSender)\- {ClientCommandSender.notifying-state-listeners}Notifying command client sender state listeners of a state change - sender is sending=[false]
2015-10-16 15:45:17,841 DEBUG [main](enterprise.communications.command.client.CommandQueue)\- {CommandQueue.disabled}Command Queue is not throttling - commands will be dequeued as fast as possible
2015-10-16 15:45:17,841 DEBUG [main](enterprise.communications.command.client.SendThrottle)\- {SendThrottle.disabled}Send throttling is disabled - commands will be sent as fast as possible
2015-10-16 15:45:17,842 INFO  [main](org.rhq.enterprise.communications.ServiceContainer)\- {ServiceContainer.shutting-down}Service container shutting down...
2015-10-16 15:45:17,842 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped threads in clientpool
2015-10-16 15:45:17,842 DEBUG [ServerSocketRefresh](jboss.remoting.transport.socket.SocketServerInvoker)\- ServerSocketRefresh shutting down
2015-10-16 15:45:17,842 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped threads in threadpool
2015-10-16 15:45:17,842 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] exiting
2015-10-16 15:45:17,846 DEBUG [main](org.jboss.remoting.ServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped
2015-10-16 15:45:17,847 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [echo] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=1]
2015-10-16 15:45:17,847 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [identify] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=2]
2015-10-16 15:45:17,847 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [remotepojo] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=3]
2015-10-16 15:45:17,848 INFO  [main](org.rhq.enterprise.communications.ServiceContainer)\- {ServiceContainer.shutdown}Service container shut down - no longer accepting incoming commands
2015-10-16 15:45:17,848 INFO  [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.shut-down}Agent has been shut down
2015-10-16 15:45:17,848 FATAL [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.start-failure}Failed to start the agent
org.rhq.core.clientapi.server.core.AgentRegistrationException: The agent cannot register with the server. Admin intervention needed!
        at org.rhq.enterprise.agent.AgentMain.start(AgentMain.java:744)
        at org.rhq.enterprise.agent.AgentMain.main(AgentMain.java:461)

**Comment by rafaeltuelho** [comment]
Hi @rgupta1234 

There are other agents with this same problem? What about the other containers? 

Did you have problem starting the `dnsmasq` container?
After enabling the Firewall service in the Host @jgammon612 managed to get this setup working.
See the issue #4 comments.

**Comment by rgupta1234** [comment]
Yes, think all the agents have this problem
other containers are up 

I enabled the firewall service
[root@localhost yum.repos.d]# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                                                                                                           NAMES
55047e63d8eb        rsoares/jon-server:latest     "/run.sh"                About an hour ago   Up About an hour    0.0.0.0:7080->7080/tcp                                                                                                                          jbosseapmanagedondocker_jonserver_1
3675874498a4        rsoares/eap:latest            "/run.sh domain --hos"   About an hour ago   Up About an hour    4447/tcp, 5455/tcp, 7500/tcp, 8080/tcp, 9990/tcp, 9999/tcp, 23364/tcp, 45688/tcp, 45700/tcp, 54200/tcp, 55200/tcp                               jbosseapmanagedondocker_eapslave2_1
102c2b64995f        rsoares/ews:latest            "/run.sh"                About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:6666->6666/tcp                                                                                                      jbosseapmanagedondocker_ewshttpd_1
a00578b5bab7        rsoares/jon-postgres:latest   "/run.sh"                About an hour ago   Up About an hour    5432/tcp, 16163/tcp                                                                                                                             jbosseapmanagedondocker_jonpostgres_1
e39a8bb6d6c6        rsoares/eap:latest            "/run.sh domain --hos"   About an hour ago   Up About an hour    4447/tcp, 5455/tcp, 7500/tcp, 8080/tcp, 9990/tcp, 9999/tcp, 23364/tcp, 45688/tcp, 45700/tcp, 54200/tcp, 55200/tcp                               jbosseapmanagedondocker_eapslave1_1
5672c553083a        rsoares/eap:latest            "/run.sh domain --hos"   About an hour ago   Up About an hour    4447/tcp, 5455/tcp, 7500/tcp, 0.0.0.0:9990->9990/tcp, 8080/tcp, 23364/tcp, 45688/tcp, 45700/tcp, 54200/tcp, 55200/tcp, 0.0.0.0:9999->9999/tcp   jbosseapmanagedondocker_eapmaster_1
06ae135f072e        rsoares/dnsmasq:latest        "/run.sh"                About an hour ago   Up About an hour    53/tcp, 172.17.42.1:53->53/udp                                                                                                                  jbosseapmanagedondocker_dnsmasq_1

**Comment by rafaeltuelho** [comment]
Access one of the containers and and try to restart the agent:

for example:

```
docker exec -ti jbosseapmanagedondocker_eapmaster_1 /bin/bash
```

```
[root@master /]# /opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh status
```

try to restart the rhq-agent

```
/opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh restart
```

See the logs:

```
[root@master /]# tail -100f /opt/redhat/rhq-agent/logs/agent.log
```

**Comment by rgupta1234** [comment]
yes, see below, all looks okay, but then .... error 

[root@eap-slave2 /]# /opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh status 
rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin 
rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh 
rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid 
RHQ Agent (pid 1016 ) is ✘down 
[root@eap-slave2 /]# /opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh restart 
rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin 
rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh 
rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid 
rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin 
rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh 
rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid 
RHQ Agent (pid 1016 ) is ✘down 
rhq-agent-wrapper.sh: Removing existing pidfile 
rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin 
rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh 
rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid 
Starting RHQ Agent... 
rhq-agent-wrapper.sh: Start script found here: /opt/redhat/rhq-agent/bin/rhq-agent.sh 
rhq-agent-wrapper.sh: Executing agent with command: '/opt/redhat/rhq-agent/bin/rhq-agent.sh' 
RHQ Agent (pid 1180 ) is ✔running 

d as fast as possible 
2015-10-16 17:09:23,856 DEBUG [main](enterprise.communications.command.client.SendThrottle)\- {SendThrottle.disabled}Send throttling is disabled - commands will be sent as fast as possible 
2015-10-16 17:09:23,857 INFO [main](org.rhq.enterprise.communications.ServiceContainer)\- {ServiceContainer.shutting-down}Service container shutting down... 
2015-10-16 17:09:23,858 DEBUG [ServerSocketRefresh](jboss.remoting.transport.socket.SocketServerInvoker)\- ServerSocketRefresh shutting down 
2015-10-16 17:09:23,858 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped threads in clientpool 
2015-10-16 17:09:23,858 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped threads in threadpool 
2015-10-16 17:09:23,858 DEBUG [main](jboss.remoting.transport.socket.SocketServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] exiting 
2015-10-16 17:09:23,861 DEBUG [main](org.jboss.remoting.ServerInvoker)\- SocketServerInvoker[172.17.0.26:16163] stopped 
2015-10-16 17:09:23,862 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [echo] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=1] 
2015-10-16 17:09:23,862 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [identify] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=2] 
2015-10-16 17:09:23,863 DEBUG [main](enterprise.communications.command.server.CommandServiceDirectory)\- {CommandServiceDirectory.removed-command-support}Command [remotepojo] is no longer supported; removed [rhq.remoting:type=command,subsystem=RHQ,id=3] 
2015-10-16 17:09:23,863 INFO [main](org.rhq.enterprise.communications.ServiceContainer)\- {ServiceContainer.shutdown}Service container shut down - no longer accepting incoming commands 
2015-10-16 17:09:23,863 INFO [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.shut-down}Agent has been shut down 
2015-10-16 17:09:23,864 FATAL [main](org.rhq.enterprise.agent.AgentMain)\- {AgentMain.start-failure}Failed to start the agent 
org.rhq.core.clientapi.server.core.AgentRegistrationException: The agent cannot register with the server. Admin intervention needed! 
at org.rhq.enterprise.agent.AgentMain.start(AgentMain.java:744) 
at org.rhq.enterprise.agent.AgentMain.main(AgentMain.java:461) 

----- Original Message -----

**Comment by rafaeltuelho** [comment]
Hummm

I don't know why this is happening. Can be many things. JON Agent registration issues is boring to troubleshoot manually. We could enter into each container and reset the agents registration. But is a painful task.

Did you tried to kill this compose instance and start again?

**Comment by rgupta1234** [comment]
20 times, yeah .. .I just don't know what to do 
Thx though 

----- Original Message -----

**Comment by rafaeltuelho** [comment]
can you log into JON Sevrer GUI?
Access the Administration menu and open the Agents View.
If you can see the agents you can see the registration and its endpoints. 
Try to remove them from the server registration and restart the agents manually. Try to do this with one and see if it can be registered after the agent restart.

**Comment by rafaeltuelho** [comment]
@rgupta1234,

I made various tests in different environments (RHEL 7, Fedora 22 and Mac OS X). I suppose the root cause of the issues reported until now has to do with the proper firewall configuration that affects the `dnsmasq` service. 

I made some improvements on `README` instructions to highlight some points, prereqs and troubleshooting. I changed the `prepare.sh` also to check some prereqs.

If you have time and interest please give it a try! ;-)

Update you local repo:

```
git pull
```

and execute the `prepare.sh` script again to validate and rebuild the docker images used in our setup.

I will appreciate any feedback.
Thx.
